### ISSUE TITLE
bundle install: Failed to build gem native extension

### ISSUE THREAD

**Issue by fauzieuy** [jalagrange/excel_test_app#1]
i have git clone excel_test_app
I got the below error while the bundle install, This does not happen with other applications.

following error

Installing mysql2 (0.3.6) with native extensions
Gem::Installer::ExtensionBuildError: ERROR: Failed to build gem native extension
.

```
    C:/RailsInstaller/Ruby1.9.3/bin/ruby.exe extconf.rb
```

 checking for rb_thread_blocking_region()... yes
checking for main() in -llibmysql... no
**\* extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of
necessary libraries and/or headers.  Check the mkmf.log file for more
details.  You may need configuration options.

**Comment by jalagrange** [comment]
Hello, you probably don't have MySQL installed and depend on SQLite. Thats fine, the app should also run, you just have to make adjustments to your gemfile and config/database.yml.

Remove the the mysql gem from your gem file and replace it with: gem 'sqlite3'

and your database.yml should look something like this:

# SQLite version 3.x

# gem install sqlite3

#

# Ensure the SQLite 3 gem is defined in your Gemfile

# gem 'sqlite3'

development:
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 5000

# Warning: The database defined as "test" will be erased and

# re-generated from your development database when you run "rake".

# Do not set this db to the same as development or production.

test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000

production:
  adapter: sqlite3
  database: db/production.sqlite3
  pool: 5
  timeout: 5000

Hope this helps!

**Comment by fauzieuy** [comment]
problem solved this issue
i using mysql for dbms

Run "bundle update" worked for me,

but When run rake db:migrate

==  AddPropertyIdToPhoto: migrating ===========================================
-- add_column(:photos, :property_id, :integer)
rake aborted!
An error has occurred, all later migrations canceled:

Mysql2::Error: Table 'excel_development.photos' doesn't exist: ALTER TABLE `phot
os` ADD `property_id` int(11)

Tasks: TOP => db:migrate
(See full trace by running task with --trace)

**Comment by jalagrange** [comment]
ok, as the error explains, the migration was trying to chang a table which doesn't exist yet. For some reason, the order of the migrations had changed. Nevertheless i just fixed this, soo feel free to try again.

**Comment by fauzieuy** [comment]
solved, delete file add_property_id_to_photo.rb..
